// frontend-ang/src/app/module/admin/view/doc/document-admin/view-admin/document-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {DocumentService} from 'src/app/controller/service/Document.service';
import {DocumentDto} from 'src/app/controller/model/Document.model';
import {DocumentCriteria} from 'src/app/controller/criteria/DocumentCriteria.model';

import {GroupeDto} from 'src/app/controller/model/Groupe.model';
import {GroupeService} from 'src/app/controller/service/Groupe.service';
import {DocumentTypeDto} from 'src/app/controller/model/DocumentType.model';
import {DocumentTypeService} from 'src/app/controller/service/DocumentType.service';
import {TagDto} from 'src/app/controller/model/Tag.model';
import {TagService} from 'src/app/controller/service/Tag.service';
import {EntiteAdministrativeDto} from 'src/app/controller/model/EntiteAdministrative.model';
import {EntiteAdministrativeService} from 'src/app/controller/service/EntiteAdministrative.service';
import {AcessManagementDto} from 'src/app/controller/model/AcessManagement.model';
import {AcessManagementService} from 'src/app/controller/service/AcessManagement.service';
import {DocumentTagDto} from 'src/app/controller/model/DocumentTag.model';
import {DocumentTagService} from 'src/app/controller/service/DocumentTag.service';
import {UtilisateurDto} from 'src/app/controller/model/Utilisateur.model';
import {UtilisateurService} from 'src/app/controller/service/Utilisateur.service';
import {DocumentManagementGroupeDto} from 'src/app/controller/model/DocumentManagementGroupe.model';
import {DocumentManagementGroupeService} from 'src/app/controller/service/DocumentManagementGroupe.service';
import {AcessShareDto} from 'src/app/controller/model/AcessShare.model';
import {AcessShareService} from 'src/app/controller/service/AcessShare.service';
import {DocumentPartageUtilisateurDto} from 'src/app/controller/model/DocumentPartageUtilisateur.model';
import {DocumentPartageUtilisateurService} from 'src/app/controller/service/DocumentPartageUtilisateur.service';
import {DocumentManagementUtilisateurDto} from 'src/app/controller/model/DocumentManagementUtilisateur.model';
import {DocumentManagementUtilisateurService} from 'src/app/controller/service/DocumentManagementUtilisateur.service';
import {DocumentPartageGroupeDto} from 'src/app/controller/model/DocumentPartageGroupe.model';
import {DocumentPartageGroupeService} from 'src/app/controller/service/DocumentPartageGroupe.service';
import {DocumentAcessShareDto} from 'src/app/controller/model/DocumentAcessShare.model';
import {DocumentAcessShareService} from 'src/app/controller/service/DocumentAcessShare.service';
@Component({
  selector: 'app-document-view-admin',
  templateUrl: './document-view-admin.component.html'
})
export class DocumentViewAdminComponent extends AbstractViewController<DocumentDto, DocumentCriteria, DocumentService> implements OnInit {

    documentPartageGroupes = new DocumentPartageGroupeDto();
    documentPartageGroupess: Array<DocumentPartageGroupeDto> = [];
    documentPartageUtilisateurs = new DocumentPartageUtilisateurDto();
    documentPartageUtilisateurss: Array<DocumentPartageUtilisateurDto> = [];
    documentManagementGroupes = new DocumentManagementGroupeDto();
    documentManagementGroupess: Array<DocumentManagementGroupeDto> = [];
    documentManagementUtilisateurs = new DocumentManagementUtilisateurDto();
    documentManagementUtilisateurss: Array<DocumentManagementUtilisateurDto> = [];
    documentAcessShares = new DocumentAcessShareDto();
    documentAcessSharess: Array<DocumentAcessShareDto> = [];
    documentTags = new DocumentTagDto();
    documentTagss: Array<DocumentTagDto> = [];

    constructor(private documentService: DocumentService, private groupeService: GroupeService, private documentTypeService: DocumentTypeService, private tagService: TagService, private entiteAdministrativeService: EntiteAdministrativeService, private acessManagementService: AcessManagementService, private documentTagService: DocumentTagService, private utilisateurService: UtilisateurService, private documentManagementGroupeService: DocumentManagementGroupeService, private acessShareService: AcessShareService, private documentPartageUtilisateurService: DocumentPartageUtilisateurService, private documentManagementUtilisateurService: DocumentManagementUtilisateurService, private documentPartageGroupeService: DocumentPartageGroupeService, private documentAcessShareService: DocumentAcessShareService){
        super(documentService);
    }

    ngOnInit(): void {
        this.documentPartageGroupes.groupe = new GroupeDto();
        this.groupeService.findAll().subscribe((data) => this.groupes = data);
        this.documentPartageGroupes.acessShare = new AcessShareDto();
        this.acessShareService.findAll().subscribe((data) => this.acessShares = data);
        this.documentPartageUtilisateurs.utilisateur = new UtilisateurDto();
        this.utilisateurService.findAll().subscribe((data) => this.utilisateurs = data);
        this.documentPartageUtilisateurs.acessShare = new AcessShareDto();
        this.acessShareService.findAll().subscribe((data) => this.acessShares = data);
        this.documentManagementGroupes.groupe = new GroupeDto();
        this.groupeService.findAll().subscribe((data) => this.groupes = data);
        this.documentManagementGroupes.acessManagement = new AcessManagementDto();
        this.acessManagementService.findAll().subscribe((data) => this.acessManagements = data);
        this.documentManagementUtilisateurs.utilisateur = new UtilisateurDto();
        this.utilisateurService.findAll().subscribe((data) => this.utilisateurs = data);
        this.documentManagementUtilisateurs.acessManagement = new AcessManagementDto();
        this.acessManagementService.findAll().subscribe((data) => this.acessManagements = data);
        this.documentAcessShares.acessShare = new AcessShareDto();
        this.acessShareService.findAll().subscribe((data) => this.acessShares = data);
        this.documentTags.tag = new TagDto();
        this.tagService.findAll().subscribe((data) => this.tags = data);
        this.documentType = new DocumentTypeDto();
        this.documentTypeService.findAll().subscribe((data) => this.documentTypes = data);
        this.utilisateur = new UtilisateurDto();
        this.utilisateurService.findAll().subscribe((data) => this.utilisateurs = data);
        this.entiteAdministrative = new EntiteAdministrativeDto();
        this.entiteAdministrativeService.findAll().subscribe((data) => this.entiteAdministratives = data);
    }


    get utilisateur(): UtilisateurDto {
       return this.utilisateurService.item;
    }
    set utilisateur(value: UtilisateurDto) {
        this.utilisateurService.item = value;
    }
    get utilisateurs():Array<UtilisateurDto> {
       return this.utilisateurService.items;
    }
    set utilisateurs(value: Array<UtilisateurDto>) {
        this.utilisateurService.items = value;
    }
    get entiteAdministrative(): EntiteAdministrativeDto {
       return this.entiteAdministrativeService.item;
    }
    set entiteAdministrative(value: EntiteAdministrativeDto) {
        this.entiteAdministrativeService.item = value;
    }
    get entiteAdministratives():Array<EntiteAdministrativeDto> {
       return this.entiteAdministrativeService.items;
    }
    set entiteAdministratives(value: Array<EntiteAdministrativeDto>) {
        this.entiteAdministrativeService.items = value;
    }
    get groupe(): GroupeDto {
       return this.groupeService.item;
    }
    set groupe(value: GroupeDto) {
        this.groupeService.item = value;
    }
    get groupes():Array<GroupeDto> {
       return this.groupeService.items;
    }
    set groupes(value: Array<GroupeDto>) {
        this.groupeService.items = value;
    }
    get documentType(): DocumentTypeDto {
       return this.documentTypeService.item;
    }
    set documentType(value: DocumentTypeDto) {
        this.documentTypeService.item = value;
    }
    get documentTypes():Array<DocumentTypeDto> {
       return this.documentTypeService.items;
    }
    set documentTypes(value: Array<DocumentTypeDto>) {
        this.documentTypeService.items = value;
    }
    get tag(): TagDto {
       return this.tagService.item;
    }
    set tag(value: TagDto) {
        this.tagService.item = value;
    }
    get tags():Array<TagDto> {
       return this.tagService.items;
    }
    set tags(value: Array<TagDto>) {
        this.tagService.items = value;
    }
    get acessManagement(): AcessManagementDto {
       return this.acessManagementService.item;
    }
    set acessManagement(value: AcessManagementDto) {
        this.acessManagementService.item = value;
    }
    get acessManagements():Array<AcessManagementDto> {
       return this.acessManagementService.items;
    }
    set acessManagements(value: Array<AcessManagementDto>) {
        this.acessManagementService.items = value;
    }
    get acessShare(): AcessShareDto {
       return this.acessShareService.item;
    }
    set acessShare(value: AcessShareDto) {
        this.acessShareService.item = value;
    }
    get acessShares():Array<AcessShareDto> {
       return this.acessShareService.items;
    }
    set acessShares(value: Array<AcessShareDto>) {
        this.acessShareService.items = value;
    }


}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'documentTabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'documentTabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'Reference' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Reference' | translate}}" autofocus  id="1" [(ngModel)]="item.reference">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'Upload date' | translate}}</label>
                        <p-calendar id="2" [disabled]="true"  [showTime]="true" [showSeconds]="false" placeholder="{{'Upload date' | translate}}"  [(ngModel)]="item.uploadDate" dateFormat="{{dateFormat}}"></p-calendar>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'Date last update' | translate}}</label>
                        <p-calendar id="3" [disabled]="true"  [showTime]="true" [showSeconds]="false" placeholder="{{'Date last update' | translate}}"  [(ngModel)]="item.dateLastUpdate" dateFormat="{{dateFormat}}"></p-calendar>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="4">{{'Content' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Content' | translate}}" autofocus  id="4" [(ngModel)]="item.content">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="5">{{'Size' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="5" [disabled]="true" placeholder="{{'Size' | translate}}" [(ngModel)]="item.size"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="6">{{'Document type' | translate}}</label>
                        <p-dropdown [options]="documentTypes" [(ngModel)]="item.documentType" id="6" [disabled]="true" optionLabel="libelle" placeholder="{{'Document type' | translate}}"></p-dropdown>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="7">{{'Description' | translate}}</label>
                        <textarea id="7" pInputTextarea rows="5" cols="30" [disabled]="true" placeholder="{{'Description' | translate}}"  [(ngModel)]="item.description"></textarea>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="8">{{'Utilisateur' | translate}}</label>
                        <p-dropdown [options]="utilisateurs" [(ngModel)]="item.utilisateur" id="8" [disabled]="true" optionLabel="name" placeholder="{{'Utilisateur' | translate}}"></p-dropdown>
                    </div>
                    <div class="field align-inputswitch col-12  md:col-6">
                        <div  class="label-inputswitch">
                            <label for="9">{{'Archive' | translate}}</label>
                        </div>
                        <div class="input-switch">
                            <p-inputSwitch id="9"  [disabled]="true" [(ngModel)]="item.archive"></p-inputSwitch>
                        </div>
                    </div>
                    <div class="field align-inputswitch col-12  md:col-6">
                        <div  class="label-inputswitch">
                            <label for="10">{{'Versionne' | translate}}</label>
                        </div>
                        <div class="input-switch">
                            <p-inputSwitch id="10"  [disabled]="true" [(ngModel)]="item.versionne"></p-inputSwitch>
                        </div>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="11">{{'Entite administrative' | translate}}</label>
                        <p-dropdown [options]="entiteAdministratives" [(ngModel)]="item.entiteAdministrative" id="11" [disabled]="true" optionLabel="libelle" placeholder="{{'Entite administrative' | translate}}"></p-dropdown>
                    </div>
                </div>
            </p-tabPanel>

            <p-tabPanel header="{{'documentDocumentPartageGroupes' | translate}}">
                <div class="grid">
                    <div class="col">
                        <div class="card">
                            <p-table [value]="item.documentPartageGroupes" [scrollable]="true" scrollHeight="200px">
                                <ng-template pTemplate="header">
                                    <tr>
                                        <th>Groupe</th>
                                        <th>Date share</th>
                                        <th>Acess share</th>
                                    </tr>
                                </ng-template>
                                <ng-template pTemplate="body" let-p>
                                    <tr>
                                        <td>{{p.groupe?.libelle}}</td>
                                        <td>{{p.dateShare | date: dateFormatColumn}}</td>
                                        <td>{{p.acessShare?.libelle}}</td>
                                    </tr>
                                </ng-template>
                            </p-table>
                        </div>
                    </div>
                </div>
            </p-tabPanel>
            <p-tabPanel header="{{'documentDocumentPartageUtilisateurs' | translate}}">
                <div class="grid">
                    <div class="col">
                        <div class="card">
                            <p-table [value]="item.documentPartageUtilisateurs" [scrollable]="true" scrollHeight="200px">
                                <ng-template pTemplate="header">
                                    <tr>
                                        <th>Utilisateur</th>
                                        <th>Date share</th>
                                        <th>Acess share</th>
                                    </tr>
                                </ng-template>
                                <ng-template pTemplate="body" let-p>
                                    <tr>
                                        <td>{{p.utilisateur?.name}}</td>
                                        <td>{{p.dateShare | date: dateFormatColumn}}</td>
                                        <td>{{p.acessShare?.libelle}}</td>
                                    </tr>
                                </ng-template>
                            </p-table>
                        </div>
                    </div>
                </div>
            </p-tabPanel>
            <p-tabPanel header="{{'documentDocumentManagementGroupes' | translate}}">
                <div class="grid">
                    <div class="col">
                        <div class="card">
                            <p-table [value]="item.documentManagementGroupes" [scrollable]="true" scrollHeight="200px">
                                <ng-template pTemplate="header">
                                    <tr>
                                        <th>Groupe</th>
                                        <th>Date management</th>
                                        <th>Acess management</th>
                                    </tr>
                                </ng-template>
                                <ng-template pTemplate="body" let-p>
                                    <tr>
                                        <td>{{p.groupe?.libelle}}</td>
                                        <td>{{p.dateManagement | date: dateFormatColumn}}</td>
                                        <td>{{p.acessManagement?.libelle}}</td>
                                    </tr>
                                </ng-template>
                            </p-table>
                        </div>
                    </div>
                </div>
            </p-tabPanel>
            <p-tabPanel header="{{'documentDocumentManagementUtilisateurs' | translate}}">
                <div class="grid">
                    <div class="col">
                        <div class="card">
                            <p-table [value]="item.documentManagementUtilisateurs" [scrollable]="true" scrollHeight="200px">
                                <ng-template pTemplate="header">
                                    <tr>
                                        <th>Utilisateur</th>
                                        <th>Date management</th>
                                        <th>Acess management</th>
                                    </tr>
                                </ng-template>
                                <ng-template pTemplate="body" let-p>
                                    <tr>
                                        <td>{{p.utilisateur?.name}}</td>
                                        <td>{{p.dateManagement | date: dateFormatColumn}}</td>
                                        <td>{{p.acessManagement?.libelle}}</td>
                                    </tr>
                                </ng-template>
                            </p-table>
                        </div>
                    </div>
                </div>
            </p-tabPanel>
        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>

// frontend-react/pages/module/admin/view/doc/document-admin/view-admin/document-view-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";
import  {DocumentDto}  from '/pages/controller/model/Document.model';

const View = ({visible,onClose,selectedItem}) => {

    const emptyItem = new DocumentDto();
    const [item, setItem] = useState<DocumentDto>(emptyItem);
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);

    useEffect(() => {
        setItem(selectedItem ? { ...selectedItem } : { ...emptyItem });
    }, [selectedItem]);

    const onTabChange = (e: { index: number }) => {
        setActiveIndex(e.index);
    };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} /> < />
    );

return(
<Dialog visible={visible} style={{width: '70vw'}} header="Document Details" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header="Document">
    <div className="formgrid grid">

            <div className="field col-6">
                <label htmlFor="reference">Reference</label>
                <InputText id="reference" value={selectedItem?.reference} disabled   />
            </div>

        <div className="field col-6">
            <label htmlFor="uploadDate">UploadDate</label>
            <Calendar id="uploadDate" value={selectedItem?.uploadDate} disabled dateFormat="dd/mm/yy" showTime />
        </div>

        <div className="field col-6">
            <label htmlFor="dateLastUpdate">DateLastUpdate</label>
            <Calendar id="dateLastUpdate" value={selectedItem?.dateLastUpdate} disabled dateFormat="dd/mm/yy" showTime />
        </div>

            <div className="field col-6">
                <label htmlFor="content">Content</label>
                <InputText id="content" value={selectedItem?.content} disabled   />
            </div>

                <div className="field col-6">
                    <label htmlFor="size">Size</label>
                    <InputNumber id="size" value={item.size} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="documentType">DocumentType</label>
                    <Dropdown  id="documentTypeDropdown"  value={selectedItem?.documentType?.libelle}  disabled  />
                </div>
            <div className="field col-6">
                <label htmlFor="description">Description</label>
                <span className="p-float-label">
                   <InputTextarea id="description" value={selectedItem?.description} disabled rows={5} cols={30} />
                </span>
            </div>

                <div className="field col-6">
                    <label htmlFor="utilisateur">Utilisateur</label>
                    <Dropdown  id="utilisateurDropdown"  value={selectedItem?.utilisateur?.name}  disabled  />
                </div>
        <div className="field col-6">
            <div  class="label-inputswitch">
                <label htmlFor="archive">Archive</label>
                <span className="p-float-label">
            <InputSwitch  id="archive" checked={selectedItem?.archive} disabled />
             </span>
            </div>
            </div>

        <div className="field col-6">
            <div  class="label-inputswitch">
                <label htmlFor="versionne">Versionne</label>
                <span className="p-float-label">
            <InputSwitch  id="versionne" checked={selectedItem?.versionne} disabled />
             </span>
            </div>
            </div>

                <div className="field col-6">
                    <label htmlFor="entiteAdministrative">EntiteAdministrative</label>
                    <Dropdown  id="entiteAdministrativeDropdown"  value={selectedItem?.entiteAdministrative?.libelle}  disabled  />
                </div>
        </div>
</TabPanel>
    <TabPanel header="Document partage groupes">
                <div className="card">
                    <DataTable value={selectedItem?.documentPartageGroupes} tableStyle={{minWidth: '50rem'}} dataKey="id">
                                <Column field="groupe.libelle" header="Groupe"></Column>
                                <Column field="dateShare" header="Date share"></Column>
                                <Column field="acessShare.libelle" header="Acess share"></Column>
                    </DataTable>
                </div>
        </TabPanel>
    <TabPanel header="Document partage utilisateurs">
                <div className="card">
                    <DataTable value={selectedItem?.documentPartageUtilisateurs} tableStyle={{minWidth: '50rem'}} dataKey="id">
                                <Column field="utilisateur.name" header="Utilisateur"></Column>
                                <Column field="dateShare" header="Date share"></Column>
                                <Column field="acessShare.libelle" header="Acess share"></Column>
                    </DataTable>
                </div>
        </TabPanel>
    <TabPanel header="Document management groupes">
                <div className="card">
                    <DataTable value={selectedItem?.documentManagementGroupes} tableStyle={{minWidth: '50rem'}} dataKey="id">
                                <Column field="groupe.libelle" header="Groupe"></Column>
                                <Column field="dateManagement" header="Date management"></Column>
                                <Column field="acessManagement.libelle" header="Acess management"></Column>
                    </DataTable>
                </div>
        </TabPanel>
    <TabPanel header="Document management utilisateurs">
                <div className="card">
                    <DataTable value={selectedItem?.documentManagementUtilisateurs} tableStyle={{minWidth: '50rem'}} dataKey="id">
                                <Column field="utilisateur.name" header="Utilisateur"></Column>
                                <Column field="dateManagement" header="Date management"></Column>
                                <Column field="acessManagement.libelle" header="Acess management"></Column>
                    </DataTable>
                </div>
        </TabPanel>
</TabView>
</Dialog>
);
};
export default View;
