// frontend-ang/src/app/module/admin/view/doc/document-admin/list-admin/document-list-admin.component.ts
import {Component, OnInit} from '@angular/core';
import {DocumentService} from 'src/app/controller/service/Document.service';
import {DocumentDto} from 'src/app/controller/model/Document.model';
import {DocumentCriteria} from 'src/app/controller/criteria/DocumentCriteria.model';
import {AbstractListController} from 'src/app/zynerator/controller/AbstractListController';
import { environment } from 'src/environments/environment';

import {GroupeDto} from 'src/app/controller/model/Groupe.model';
import {GroupeService} from 'src/app/controller/service/Groupe.service';
import {DocumentTypeDto} from 'src/app/controller/model/DocumentType.model';
import {DocumentTypeService} from 'src/app/controller/service/DocumentType.service';
import {TagDto} from 'src/app/controller/model/Tag.model';
import {TagService} from 'src/app/controller/service/Tag.service';
import {EntiteAdministrativeDto} from 'src/app/controller/model/EntiteAdministrative.model';
import {EntiteAdministrativeService} from 'src/app/controller/service/EntiteAdministrative.service';
import {AcessManagementDto} from 'src/app/controller/model/AcessManagement.model';
import {AcessManagementService} from 'src/app/controller/service/AcessManagement.service';
import {DocumentTagDto} from 'src/app/controller/model/DocumentTag.model';
import {DocumentTagService} from 'src/app/controller/service/DocumentTag.service';
import {UtilisateurDto} from 'src/app/controller/model/Utilisateur.model';
import {UtilisateurService} from 'src/app/controller/service/Utilisateur.service';
import {DocumentManagementGroupeDto} from 'src/app/controller/model/DocumentManagementGroupe.model';
import {DocumentManagementGroupeService} from 'src/app/controller/service/DocumentManagementGroupe.service';
import {AcessShareDto} from 'src/app/controller/model/AcessShare.model';
import {AcessShareService} from 'src/app/controller/service/AcessShare.service';
import {DocumentPartageUtilisateurDto} from 'src/app/controller/model/DocumentPartageUtilisateur.model';
import {DocumentPartageUtilisateurService} from 'src/app/controller/service/DocumentPartageUtilisateur.service';
import {DocumentManagementUtilisateurDto} from 'src/app/controller/model/DocumentManagementUtilisateur.model';
import {DocumentManagementUtilisateurService} from 'src/app/controller/service/DocumentManagementUtilisateur.service';
import {DocumentPartageGroupeDto} from 'src/app/controller/model/DocumentPartageGroupe.model';
import {DocumentPartageGroupeService} from 'src/app/controller/service/DocumentPartageGroupe.service';
import {DocumentAcessShareDto} from 'src/app/controller/model/DocumentAcessShare.model';
import {DocumentAcessShareService} from 'src/app/controller/service/DocumentAcessShare.service';


@Component({
  selector: 'app-document-list-admin',
  templateUrl: './document-list-admin.component.html'
})
export class DocumentListAdminComponent extends AbstractListController<DocumentDto, DocumentCriteria, DocumentService>  implements OnInit {

    fileName = 'Document';

     yesOrNoArchive :any[] =[];
     yesOrNoVersionne :any[] =[];
    documentTypes :Array<DocumentTypeDto>;
    utilisateurs :Array<UtilisateurDto>;
    entiteAdministratives :Array<EntiteAdministrativeDto>;

constructor( private documentService: DocumentService , private groupeService: GroupeService, private documentTypeService: DocumentTypeService, private tagService: TagService, private entiteAdministrativeService: EntiteAdministrativeService, private acessManagementService: AcessManagementService, private documentTagService: DocumentTagService, private utilisateurService: UtilisateurService, private documentManagementGroupeService: DocumentManagementGroupeService, private acessShareService: AcessShareService, private documentPartageUtilisateurService: DocumentPartageUtilisateurService, private documentManagementUtilisateurService: DocumentManagementUtilisateurService, private documentPartageGroupeService: DocumentPartageGroupeService, private documentAcessShareService: DocumentAcessShareService) {
        super(documentService);
    }

    ngOnInit() : void {
      this.findPaginatedByCriteria();
      this.initExport();
      this.initCol();
      this.loadDocumentType();
      this.loadUtilisateur();
      this.loadEntiteAdministrative();
    this.yesOrNoArchive =  [{label: 'Archive', value: null},{label: 'Oui', value: 1},{label: 'Non', value: 0}];
    this.yesOrNoVersionne =  [{label: 'Versionne', value: null},{label: 'Oui', value: 1},{label: 'Non', value: 0}];
    }

    public async loadDocuments(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('Document', 'list');
        isPermistted ? this.service.findAll().subscribe(documents => this.items = documents,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'erreur', detail: 'problème d\'autorisation'});
    }


    public initCol() {
        this.cols = [
            {field: 'reference', header: 'Reference'},
            {field: 'uploadDate', header: 'Upload date'},
            {field: 'dateLastUpdate', header: 'Date last update'},
            {field: 'content', header: 'Content'},
            {field: 'size', header: 'Size'},
            {field: 'documentType?.libelle', header: 'Document type'},
            {field: 'utilisateur?.name', header: 'Utilisateur'},
            {field: 'archive', header: 'Archive'},
            {field: 'versionne', header: 'Versionne'},
            {field: 'entiteAdministrative?.libelle', header: 'Entite administrative'},
        ];
    }


    public async loadDocumentType(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('Document', 'list');
        isPermistted ? this.documentTypeService.findAllOptimized().subscribe(documentTypes => this.documentTypes = documentTypes,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }
    public async loadUtilisateur(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('Document', 'list');
        isPermistted ? this.utilisateurService.findAllOptimized().subscribe(utilisateurs => this.utilisateurs = utilisateurs,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }
    public async loadEntiteAdministrative(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('Document', 'list');
        isPermistted ? this.entiteAdministrativeService.findAllOptimized().subscribe(entiteAdministratives => this.entiteAdministratives = entiteAdministratives,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }

	public initDuplicate(res: DocumentDto) {
        if (res.documentPartageGroupes != null) {
             res.documentPartageGroupes.forEach(d => { d.document = null; d.id = null; });
        }
        if (res.documentPartageUtilisateurs != null) {
             res.documentPartageUtilisateurs.forEach(d => { d.document = null; d.id = null; });
        }
        if (res.documentManagementGroupes != null) {
             res.documentManagementGroupes.forEach(d => { d.document = null; d.id = null; });
        }
        if (res.documentManagementUtilisateurs != null) {
             res.documentManagementUtilisateurs.forEach(d => { d.document = null; d.id = null; });
        }
        if (res.documentAcessShares != null) {
             res.documentAcessShares.forEach(d => { d.document = null; d.id = null; });
        }
        if (res.documentTags != null) {
             res.documentTags.forEach(d => { d.document = null; d.id = null; });
        }
	}

   public prepareColumnExport() : void {
        this.exportData = this.items.map(e => {
            return {
                 'Reference': e.reference ,
                'Upload date': this.datePipe.transform(e.uploadDate , 'dd/MM/yyyy hh:mm'),
                'Date last update': this.datePipe.transform(e.dateLastUpdate , 'dd/MM/yyyy hh:mm'),
                 'Content': e.content ,
                 'Size': e.size ,
                'Document type': e.documentType?.libelle ,
                 'Description': e.description ,
                'Utilisateur': e.utilisateur?.name ,
                'Archive': e.archive? 'Vrai' : 'Faux' ,
                'Versionne': e.versionne? 'Vrai' : 'Faux' ,
                'Entite administrative': e.entiteAdministrative?.libelle ,
            }
        });

        this.criteriaData = [{
            'Reference': this.criteria.reference ? this.criteria.reference : environment.emptyForExport ,
            'Upload date Min': this.criteria.uploadDateFrom ? this.datePipe.transform(this.criteria.uploadDateFrom , this.dateFormat) : environment.emptyForExport ,
            'Upload date Max': this.criteria.uploadDateTo ? this.datePipe.transform(this.criteria.uploadDateTo , this.dateFormat) : environment.emptyForExport ,
            'Date last update Min': this.criteria.dateLastUpdateFrom ? this.datePipe.transform(this.criteria.dateLastUpdateFrom , this.dateFormat) : environment.emptyForExport ,
            'Date last update Max': this.criteria.dateLastUpdateTo ? this.datePipe.transform(this.criteria.dateLastUpdateTo , this.dateFormat) : environment.emptyForExport ,
            'Content': this.criteria.content ? this.criteria.content : environment.emptyForExport ,
            'Size Min': this.criteria.sizeMin ? this.criteria.sizeMin : environment.emptyForExport ,
            'Size Max': this.criteria.sizeMax ? this.criteria.sizeMax : environment.emptyForExport ,
        //'Document type': this.criteria.documentType?.libelle ? this.criteria.documentType?.libelle : environment.emptyForExport ,
            'Description': this.criteria.description ? this.criteria.description : environment.emptyForExport ,
        //'Utilisateur': this.criteria.utilisateur?.name ? this.criteria.utilisateur?.name : environment.emptyForExport ,
            'Archive': this.criteria.archive ? (this.criteria.archive ? environment.trueValue : environment.falseValue) : environment.emptyForExport ,
            'Versionne': this.criteria.versionne ? (this.criteria.versionne ? environment.trueValue : environment.falseValue) : environment.emptyForExport ,
        //'Entite administrative': this.criteria.entiteAdministrative?.libelle ? this.criteria.entiteAdministrative?.libelle : environment.emptyForExport ,
        }];
      }
}

<div class="grid">
    <div class="col-12">
        <p-toast></p-toast>
        <div class="card">
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                                        <button pButton pRipple label=" {{'new' | translate}}" icon="pi pi-plus" class="p-button-success mr-2 mb-2" (click)="openCreate('Document')"></button>
                    <button [disabled]="isSelectionDisabled()" pButton pRipple label=" {{'delete' | translate}}" icon="pi pi-trash" class="p-button-danger mr-2 mb-2" (click)=deleteMultiple()></button>
                    <button pButton pRipple label=" {{'search' | translate}}" icon="pi pi-{{findByCriteriaShow?'angle-down':'angle-right'}}" class="p-button-warning mr-2 mb-2" (click)="this.showSearch()"></button>
                </ng-template>
                <ng-template pTemplate="right">
                    <div class="flex">
                        <p-splitButton label=" {{'export' | translate}}" icon="pi pi-download" styleClass="p-button-help" [model]="excelPdfButons"></p-splitButton>
                    </div>
                </ng-template>

            </p-toolbar>
            <p-toolbar *ngIf="findByCriteriaShow">

                <div class="align-form-search">
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <input class="mr-2" pInputText id="1" type="text"  [(ngModel)]="criteria.referenceLike">
                            <label for="1">{{'Reference' | translate}}</label>
                        </span>

                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.uploadDateFrom"
                                    id="2-1"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="2-1">{{'Upload date' | translate}} Min</label>
                        </span>

                         <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.uploadDateTo"
                                    id="2-2"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="2-2">{{'Upload date' | translate}} Max</label>
                        </span>


                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.dateLastUpdateFrom"
                                    id="3-1"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="3-1">{{'Date last update' | translate}} Min</label>
                        </span>

                         <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.dateLastUpdateTo"
                                    id="3-2"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="3-2">{{'Date last update' | translate}} Max</label>
                        </span>

                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <input class="mr-2" pInputText id="4" type="text"  [(ngModel)]="criteria.contentLike">
                            <label for="4">{{'Content' | translate}}</label>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.sizeMin" id="5-1"></p-inputNumber>
                            <label for="5-1">{{'Size' | translate}} Min</label>
                        </span>
                       <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.sizeMax" id="5-2"></p-inputNumber>
                            <label for="5-2">{{'Size' | translate}} Max</label>
                       </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown [options]="documentTypes" [(ngModel)]="criteria.documentType" id="6" [filter]="true"
                                        [showClear]="true"  placeholder="{{'Document type' | translate}}" optionLabel="libelle">
                            </p-dropdown>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <input class="mr-2" pInputText id="7" type="text"  [(ngModel)]="criteria.descriptionLike">
                            <label for="7">{{'Description' | translate}}</label>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-multiSelect   appendTo="body" [options]="utilisateurs" [(ngModel)]="criteria.utilisateurs" itemSize="30" [virtualScroll]="true"
                                                  defaultLabel="{{'Utilisateur' | translate}}" id="8" optionLabel="name"  display="chip">
                            </p-multiSelect>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown  id="9" [options]="yesOrNoArchive" [(ngModel)]="criteria.archive"
                                    [filter]="false" [showClear]="true"  placeholder="{{'Archive' | translate}}" optionLabel="label" optionValue="value">
                            </p-dropdown>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown  id="10" [options]="yesOrNoVersionne" [(ngModel)]="criteria.versionne"
                                    [filter]="false" [showClear]="true"  placeholder="{{'Versionne' | translate}}" optionLabel="label" optionValue="value">
                            </p-dropdown>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown [options]="entiteAdministratives" [(ngModel)]="criteria.entiteAdministrative" id="11" [filter]="true"
                                        [showClear]="true"  placeholder="{{'Entite administrative' | translate}}" optionLabel="libelle">
                            </p-dropdown>
                        </span>
                </div>

                <div class="align-search-button">
                    <button pButton pRipple label="{{'validate' | translate}}" icon="pi pi-sort-amount-down" class="p-button-info mr-2" (click)="findPaginatedByCriteria()"></button>
                </div>
            </p-toolbar>


            <p-table #dt [value]="items" [columns]="cols" [rows]="8" [paginator]="false"
                    [globalFilterFields]="['reference', 'uploadDate', 'dateLastUpdate', 'content', 'size', 'documentTypelibelle', 'utilisateurname', 'archive', 'versionne', 'entiteAdministrativelibelle']" [(selection)]="selections"
                    [rowHover]="true" dataKey="id" styleClass="p-datatable-customers"
                    currentPageReportTemplate="{{'Les éléments de {first} à {last} sur {totalRecords} ' | translate}}"
                    [showCurrentPageReport]="true" [rowsPerPageOptions]="[10,25,50]" selectionMode="multiple">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column flex-row justify-content-between table-header">
                        <h5 class="p-m-0">{{'documentHeader' | translate}}</h5>
                        <span class="p-input-icon-left ml-auto">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" placeholder="{{'searchInput' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>
                                
                        <th pSortableColumn="reference">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Reference' | translate}}</span>
                                <p-sortIcon field="reference"></p-sortIcon>
                                <p-columnFilter type="text" field="element.reference" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="uploadDate">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Upload date' | translate}}</span>
                                <p-sortIcon field="uploadDate"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="dateLastUpdate">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Date last update' | translate}}</span>
                                <p-sortIcon field="dateLastUpdate"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="content">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Content' | translate}}</span>
                                <p-sortIcon field="content"></p-sortIcon>
                                <p-columnFilter type="text" field="element.content" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="size">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Size' | translate}}</span>
                                <p-sortIcon field="size"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="documentType">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Document type' | translate}}</span>
                                <p-sortIcon field="documentType"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="utilisateur">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Utilisateur' | translate}}</span>
                                <p-sortIcon field="utilisateur"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="archive">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Archive' | translate}}</span>
                                <p-sortIcon field="archive"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="versionne">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Versionne' | translate}}</span>
                                <p-sortIcon field="versionne"></p-sortIcon>
                            </div>
                        </th>
                                
                                <!-- 
                        <th pSortableColumn="entiteAdministrative">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Entite administrative' | translate}}</span>
                                <p-sortIcon field="entiteAdministrative"></p-sortIcon>
                            </div>
                        </th>
                                --> 
                        <th>Actions</th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-element>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="element"></p-tableCheckbox>
                        </td>
                            
                        <td>{{element.reference}}</td>
                            
                            
                        <td>{{element.uploadDate | date :'dd/MM/yyyy HH:mm' }}</td>
                            
                            
                        <td>{{element.dateLastUpdate | date :'dd/MM/yyyy HH:mm' }}</td>
                            
                            
                        <td>{{element.content}}</td>
                            
                            
                        <td>{{element.size}}</td>
                            
                            
                        <td>{{element.documentType?.libelle}}</td>
                            
                            
                        <td>{{element.utilisateur?.name}}</td>
                            
                            
                        <td><i *ngIf="element.archive" class="pi pi-check checked-toogle"></i>
                            <i *ngIf="!element.archive" class="pi pi-times unchecked-toogle"></i>
                        </td>
                            
                            
                        <td><i *ngIf="element.versionne" class="pi pi-check checked-toogle"></i>
                            <i *ngIf="!element.versionne" class="pi pi-times unchecked-toogle"></i>
                        </td>
                            
                             <!-- 
                        <td>{{element.entiteAdministrative?.libelle}}</td>
                             --> 
                        <td>
                            <button pButton pRipple icon="pi pi-pencil"  class="p-button-rounded p-button-success mr-2" (click)="edit(element)"></button>
                            <button pButton pRipple icon="pi pi-list" class="p-button-rounded p-button-info mr-2" (click)="view(element)"></button>
                            <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-danger mr-2" (click)="delete(element)"></button>
                            <button pButton pRipple icon="pi pi-copy" class="p-button-rounded p-button-raised p-button-warning mr-2" (click)="duplicate(element)"></button>
                        </td>
                    </tr>
                </ng-template>

                <ng-template pTemplate="summary">
                    <p-paginator  [rows]="10" [totalRecords]="totalRecords" (onPageChange)="onPage($event)"></p-paginator>
                    <div class="p-d-flex p-ai-center p-jc-between">
                        En totale il {{items ? totalRecords == 1 ? 'y a' : 'y a' : 'y a' }} {{items ? totalRecords : 0 }} {{items ? totalRecords == 1 ? 'document' : 'documents' : 0 }}.
                    </div>
                </ng-template>
            </p-table>
        </div>

        <app-document-create-admin></app-document-create-admin>
        <app-document-edit-admin></app-document-edit-admin>
        <app-document-view-admin></app-document-view-admin>
        <p-confirmDialog [style]="{width: '450px'}"></p-confirmDialog>
    </div>
</div>

// frontend-react/pages/module/admin/view/doc/document-admin/list-admin/document-list-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {FileUpload} from 'primereact/fileupload';
import {InputText} from 'primereact/inputtext';
import {Toast} from 'primereact/toast';
import {Toolbar} from 'primereact/toolbar';
import React, {useEffect, useRef, useState} from 'react';
import { Paginator } from 'primereact/paginator';
import {BaseCriteria} from '/pages/zynerator/criteria/BaseCriteria.model';
import {MessageService} from '/pages/controller/service/MessageService';
import {Card} from "primereact/card";
import {Calendar} from "primereact/calendar";
import {InputNumber} from "primereact/inputnumber";
import {Dropdown} from "primereact/dropdown";
import {AxiosResponse} from "axios";

import {DocumentService} from '/pages/controller/service/Document.service';
import {DocumentDto}  from '/pages/controller/model/Document.model';
import {DocumentCriteria} from "/pages/controller/criteria/DocumentCriteria.model";

import {DocumentManagementGroupeDto} from '/pages/controller/model/DocumentManagementGroupe.model';
import {DocumentManagementGroupeService} from '/pages/controller/service/DocumentManagementGroupe.service';
import {DocumentAcessShareDto} from '/pages/controller/model/DocumentAcessShare.model';
import {DocumentAcessShareService} from '/pages/controller/service/DocumentAcessShare.service';
import {DocumentPartageGroupeDto} from '/pages/controller/model/DocumentPartageGroupe.model';
import {DocumentPartageGroupeService} from '/pages/controller/service/DocumentPartageGroupe.service';
import {DocumentPartageUtilisateurDto} from '/pages/controller/model/DocumentPartageUtilisateur.model';
import {DocumentPartageUtilisateurService} from '/pages/controller/service/DocumentPartageUtilisateur.service';
import {DocumentTypeDto} from '/pages/controller/model/DocumentType.model';
import {DocumentTypeService} from '/pages/controller/service/DocumentType.service';
import {UtilisateurDto} from '/pages/controller/model/Utilisateur.model';
import {UtilisateurService} from '/pages/controller/service/Utilisateur.service';
import {AcessShareDto} from '/pages/controller/model/AcessShare.model';
import {AcessShareService} from '/pages/controller/service/AcessShare.service';
import {AcessManagementDto} from '/pages/controller/model/AcessManagement.model';
import {AcessManagementService} from '/pages/controller/service/AcessManagement.service';
import {DocumentTagDto} from '/pages/controller/model/DocumentTag.model';
import {DocumentTagService} from '/pages/controller/service/DocumentTag.service';
import {TagDto} from '/pages/controller/model/Tag.model';
import {TagService} from '/pages/controller/service/Tag.service';
import {DocumentManagementUtilisateurDto} from '/pages/controller/model/DocumentManagementUtilisateur.model';
import {DocumentManagementUtilisateurService} from '/pages/controller/service/DocumentManagementUtilisateur.service';
import {EntiteAdministrativeDto} from '/pages/controller/model/EntiteAdministrative.model';
import {EntiteAdministrativeService} from '/pages/controller/service/EntiteAdministrative.service';
import {GroupeDto} from '/pages/controller/model/Groupe.model';
import {GroupeService} from '/pages/controller/service/Groupe.service';

import Edit from '/pages/module/admin/view/doc/document-admin/edit-admin/document-edit-admin.component';
import Create from '/pages/module/admin/view/doc/document-admin/create-admin/document-create-admin.component';
import View from '/pages/module/admin/view/doc/document-admin/view-admin/document-view-admin.component';

const List = () => {

    const emptyItem = new DocumentDto();
    const [items, setItems] = useState<DocumentDto[]>([]);
    const [deleteItemDialog, setDeleteItemDialog] = useState(false);
    const [deleteItemsDialog, setDeleteItemsDialog] = useState(false);
    const [item, setItem] = useState<DocumentDto>(emptyItem);
    const [selectedItems, setSelectedItems] = useState<DocumentDto[]>([]);
    const [globalFilter, setGlobalFilter] = useState('');
    const [showCreateDialog, setShowCreateDialog] = useState<boolean>(false);
    const [showEditDialog, setShowEditDialog] = useState<boolean>(false);
    const [showViewDialog, setShowViewDialog] = useState<boolean>(false);
    const [selectedItem, setSelectedItem] = useState<DocumentDto | null>(null);
    const [rows, setRows] = useState<number>(10);
    const [totalRecords, setTotalRecords] = useState(0);
    const [criteria, setCriteria] = useState(new DocumentCriteria());
    const [first, setFirst] = useState(0);
    const toast = useRef<Toast>();
    const dt = useRef<DataTable<DocumentDto[]>>();
    const [findByCriteriaShow, setFindByCriteriaShow] = useState(false);
    const [isSearchTriggered, setIsSearchTriggered] = useState(false);

    const [documentManagementGroupes, setDocumentManagementGroupes] = useState<DocumentManagementGroupeDto[]>([]);
    type DocumentManagementGroupeResponse = AxiosResponse<DocumentManagementGroupeDto[]>;
    const [documentAcessShares, setDocumentAcessShares] = useState<DocumentAcessShareDto[]>([]);
    type DocumentAcessShareResponse = AxiosResponse<DocumentAcessShareDto[]>;
    const [documentPartageGroupes, setDocumentPartageGroupes] = useState<DocumentPartageGroupeDto[]>([]);
    type DocumentPartageGroupeResponse = AxiosResponse<DocumentPartageGroupeDto[]>;
    const [documentPartageUtilisateurs, setDocumentPartageUtilisateurs] = useState<DocumentPartageUtilisateurDto[]>([]);
    type DocumentPartageUtilisateurResponse = AxiosResponse<DocumentPartageUtilisateurDto[]>;
    const [documentTypes, setDocumentTypes] = useState<DocumentTypeDto[]>([]);
    type DocumentTypeResponse = AxiosResponse<DocumentTypeDto[]>;
    const [utilisateurs, setUtilisateurs] = useState<UtilisateurDto[]>([]);
    type UtilisateurResponse = AxiosResponse<UtilisateurDto[]>;
    const [acessShares, setAcessShares] = useState<AcessShareDto[]>([]);
    type AcessShareResponse = AxiosResponse<AcessShareDto[]>;
    const [acessManagements, setAcessManagements] = useState<AcessManagementDto[]>([]);
    type AcessManagementResponse = AxiosResponse<AcessManagementDto[]>;
    const [documentTags, setDocumentTags] = useState<DocumentTagDto[]>([]);
    type DocumentTagResponse = AxiosResponse<DocumentTagDto[]>;
    const [tags, setTags] = useState<TagDto[]>([]);
    type TagResponse = AxiosResponse<TagDto[]>;
    const [documentManagementUtilisateurs, setDocumentManagementUtilisateurs] = useState<DocumentManagementUtilisateurDto[]>([]);
    type DocumentManagementUtilisateurResponse = AxiosResponse<DocumentManagementUtilisateurDto[]>;
    const [entiteAdministratives, setEntiteAdministratives] = useState<EntiteAdministrativeDto[]>([]);
    type EntiteAdministrativeResponse = AxiosResponse<EntiteAdministrativeDto[]>;
    const [groupes, setGroupes] = useState<GroupeDto[]>([]);
    type GroupeResponse = AxiosResponse<GroupeDto[]>;

    const showSearch = () => { setFindByCriteriaShow(!findByCriteriaShow); };

    const handleValidateClick = () => {setIsSearchTriggered(true);};

    const handleCancelClick = () => {
        setCriteria(new DocumentCriteria());
        setIsSearchTriggered(true);
    };

    useEffect(() => {
        const fetchData = async () => {
            try {
                const [utilisateursResponse ,entiteAdministrativesResponse ,groupesResponse ,documentTypesResponse ,tagsResponse ,acessManagementsResponse ,acessSharesResponse ] = await Promise.all<UtilisateurResponse,EntiteAdministrativeResponse,GroupeResponse,DocumentTypeResponse,TagResponse,AcessManagementResponse,AcessShareResponse>([
                    DocumentTypeService.getList(),
                    TagService.getList(),
                ]);
                setUtilisateurs(utilisateursResponse.data);
                setEntiteAdministratives(entiteAdministrativesResponse.data);
                setGroupes(groupesResponse.data);
                setDocumentTypes(documentTypesResponse.data);
                setTags(tagsResponse.data);
                setAcessManagements(acessManagementsResponse.data);
                setAcessShares(acessSharesResponse.data);
            } catch (error) {
                console.error(error);
            }
        };
        if (isSearchTriggered) {
            fetchItems(criteria);
            setIsSearchTriggered(false);
        }
        fetchData();
        fetchItems(criteria);
    }, [isSearchTriggered]);

    const fetchItems = async (criteria) => {
        try {
            const response = await DocumentService.findPaginatedByCriteria(criteria);
            const paginatedItems = response.data;
            setTotalRecords(paginatedItems.dataSize);
            setItems(paginatedItems.list);
        } catch (error) {
            console.log(error);
        }
    };

    const onPage = (event) => {
        const updatedCriteria = { ...criteria, page: event.page,maxResults: event.rows };
        setCriteria(updatedCriteria);
        setFirst(event.first);
        fetchItems(updatedCriteria);
    };

    const showCreateModal = (): void => {
        setShowCreateDialog(true);
    };

    const showEditModal = (item: DocumentDto) => {
        setSelectedItem(item);
        setShowEditDialog(true);
    };

    const showViewModal = (item: DocumentDto) => {
        setSelectedItem(item);
        setShowViewDialog(true);
    };

    const add = (item) => {
        setItems([...items, item]);
    };

    const update = (updatedItem: DocumentDto) => {
        const updatedList = items.map((item) => {
            if (item.id === updatedItem.id) { return updatedItem; }
            return item;
        });
        setItems(updatedList);
    };

   const hideDeleteItemDialog = () => {
        setDeleteItemDialog(false);
   };

   const hideDeleteItemsDialog = () => {
        setDeleteItemsDialog(false);
   };

    const confirmDeleteItem = (item: DocumentDto) => {
        setSelectedItem(item);
        setDeleteItemDialog(true);
    };

    const deleteItem = async () => {
        try{
            await DocumentService.delete(selectedItem?.id);
            setDeleteItemDialog(false);
            setItem(emptyItem);
            let _items = items.filter((val) => val.id !== selectedItem?.id);
            setItems(_items);
            MessageService.showToast(toast, { severity: 'success', summary: 'Successful', detail: 'Document Deleted', life: 3000 });
        } catch (error) {
            console.log(error);
        }
    };

    const exportCSV = () => {
        dt.current?.exportCSV();
    };

    const confirmDeleteSelected = () => {
        setDeleteItemsDialog(true);
    };

    const deleteSelectedItems = async () => {
        await DocumentService.deleteList(selectedItems);
        let _items = items.filter((val) => !selectedItems.includes(val));
        setItems(_items);
        setDeleteItemsDialog(false);
        setSelectedItems(null);
        MessageService.showToast(toast, { severity: 'success', summary: 'Successful', detail: 'Documents Deleted', life: 3000 });
    };

   const leftToolbarTemplate = () => {
       return (
           <React.Fragment>
               <div className="my-2">
                   <Button label="New" icon="pi pi-plus" severity="success" className=" mr-2" onClick={ showCreateModal} />
                   <Button label="Delete" icon="pi pi-trash" severity="danger" className=" mr-2" onClick={confirmDeleteSelected} disabled={!selectedItems || !selectedItems.length} />
                   <Button label="Search" icon={`pi pi-${findByCriteriaShow ? 'angle-down' : 'angle-right'}`} className=" mr-2" severity="warning" onClick={showSearch} />
               </div>
           </React.Fragment>
       );
   };

   const rightToolbarTemplate = () => {
       return (
           <React.Fragment>
               <FileUpload mode="basic" accept="image/*" maxFileSize={1000000} chooseLabel="Import" className="mr-2 inline-block" />
               <Button label="Export" icon="pi pi-upload" severity="help" onClick={exportCSV} />
           </React.Fragment>
       );
   };

    const actionBodyTemplate = (rowData: DocumentDto) => {
       return ( <>
           <Button icon="pi pi-pencil" rounded severity="success" className="mr-1" onClick={() => showEditModal(rowData)} />
           <Button icon="pi pi-trash" rounded  severity="danger" className="mr-1"  onClick={() => confirmDeleteItem(rowData)} />
           <Button icon="pi pi-eye" rounded severity="info" className="mr-1" onClick={() => showViewModal(rowData)} /> < />
       );
    };

    const header = (
        <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
        <h5 className="m-0">Manage documents</h5>
        <span className="block mt-2 md:mt-0 p-input-icon-left"><i className="pi pi-search" />
        <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)} placeholder="Search..." /> </span>
        </div>
    );

    const deleteItemDialogFooter = ( <>
        <Button label="No" icon="pi pi-times" text onClick={hideDeleteItemDialog} />
        <Button label="Yes" icon="pi pi-check" text onClick={deleteItem} /> < />
    );

    const deleteItemsDialogFooter = ( <>
        <Button label="No" icon="pi pi-times" text onClick={hideDeleteItemsDialog} />
        <Button label="Yes" icon="pi pi-check" text onClick={deleteSelectedItems} /> < />
    );

return (
    <>
    <div className="grid crud-demo">
        <div className="col-12">
            <div className="card">
                <Toast ref={toast} />
                <Toolbar className="mb-4" left={leftToolbarTemplate} right={rightToolbarTemplate}></Toolbar>
                {findByCriteriaShow && (
                <Card>
                    <div className="search-container">
                        <div className="grid">
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputText id="1" value={criteria.reference} onChange={(e) => setCriteria({ ...criteria, reference: e.target.value })} />
                                        <label htmlFor="1">Reference</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="2-1" value={criteria.uploadDateFrom} onChange={(e) => setCriteria({ ...criteria, uploadDateFrom: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="2-1">UploadDate Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="2-2" value={criteria.uploadDateTo} onChange={(e) => setCriteria({ ...criteria, uploadDateTo: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="2-2">UploadDate Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="3-1" value={criteria.dateLastUpdateFrom} onChange={(e) => setCriteria({ ...criteria, dateLastUpdateFrom: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="3-1">DateLastUpdate Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="3-2" value={criteria.dateLastUpdateTo} onChange={(e) => setCriteria({ ...criteria, dateLastUpdateTo: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="3-2">DateLastUpdate Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputText id="4" value={criteria.content} onChange={(e) => setCriteria({ ...criteria, content: e.target.value })} />
                                        <label htmlFor="4">Content</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="5-1" value={criteria.sizeMin} onChange={(e) => setCriteria({ ...criteria, sizeMin: e.value })} mode="decimal" />
                                        <label htmlFor="5-1">Size Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="5-2" value={criteria.sizeMax} onChange={(e) => setCriteria({ ...criteria, sizeMax: e.value })} mode="decimal" />
                                        <label htmlFor="5-2">Size Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="6" value={criteria.documentType} options={documentTypes} onChange={(e) => setCriteria({ ...criteria, documentType: e.target.value })} optionLabel="libelle" filter showClear placeholder="DocumentType" />
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputText id="7" value={criteria.description} onChange={(e) => setCriteria({ ...criteria, description: e.target.value })} />
                                        <label htmlFor="7">Description</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="8" value={criteria.utilisateur} options={utilisateurs} onChange={(e) => setCriteria({ ...criteria, utilisateur: e.target.value })} optionLabel="name" filter showClear placeholder="Utilisateur" />
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="11" value={criteria.entiteAdministrative} options={entiteAdministratives} onChange={(e) => setCriteria({ ...criteria, entiteAdministrative: e.target.value })} optionLabel="libelle" filter showClear placeholder="EntiteAdministrative" />
                                        </span>
                        </div>
                        <div style={{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }} >
                            <Button label="Validate" icon="pi pi-sort-amount-down" className="p-button-info mr-2" onClick={handleValidateClick} />
                            <Button label="Cancel" className="p-button-secondary mr-2"  icon="pi pi-times" onClick={handleCancelClick} />
                    </div>
                        </div>
                </Card>
                )}
                <DataTable ref={dt} value={items} selection={selectedItems} onSelectionChange={(e) => setSelectedItems(e.value as DocumentDto[])} dataKey="id" className="datatable-responsive" globalFilter={globalFilter} header={header} responsiveLayout="scroll" >
                    <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}> </Column>
                    
                    <Column field="reference" header="Reference" sortable></Column>
                    
                    
                    <Column field="uploadDate" header="UploadDate" sortable></Column>
                    
                    
                    <Column field="dateLastUpdate" header="DateLastUpdate" sortable></Column>
                    
                    
                    <Column field="content" header="Content" sortable></Column>
                    
                    
                    <Column field="size" header="Size" sortable></Column>
                    
                    
                    <Column field="documentType.libelle" header="DocumentType" sortable></Column>
                    
                    
                    <Column field="utilisateur.name" header="Utilisateur" sortable></Column>
                    
                    
                    <Column field="archive" header="Archive" sortable></Column>
                    
                    
                    <Column field="versionne" header="Versionne" sortable></Column>
                    
{/*

                    <Column field="entiteAdministrative.libelle" header="EntiteAdministrative" sortable></Column>
*/}

                    <Column header="Actions" body={actionBodyTemplate}></Column>
                </DataTable>
                <div className="p-d-flex p-ai-center p-jc-between">
                    <Paginator onPageChange={onPage} first={first} rows={rows} totalRecords={totalRecords} />
                </div>
                <Create visible={showCreateDialog} onClose={() => setShowCreateDialog(false)} add={add} showToast={toast} list={items} />
                <Edit  visible={showEditDialog} onClose={() =>  { setShowEditDialog(false); setSelectedItem(null); }} showToast={toast} selectedItem={selectedItem} update={update} />
                <View visible={showViewDialog} onClose={() =>  { setShowViewDialog(false); setSelectedItem(null); }} selectedItem={selectedItem} />
                <Dialog visible={deleteItemDialog} style={{width: '450px'}} header="Confirm" modal footer={deleteItemDialogFooter} onHide={hideDeleteItemDialog}>
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}}/>
                    {item && (<span>Are you sure you want to delete document <b>{item.id}</b>?</span>)}
                    </div>
                </Dialog>
                <Dialog visible={deleteItemsDialog} style={{width: '450px'}} header="Confirm" modal footer={deleteItemsDialogFooter} onHide={hideDeleteItemsDialog} >
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}} />
                    {item && <span>Are you sure you want to delete the selected documents?</span>}
                    </div>
                </Dialog>
            </div>
        </div>
    </div>
    </>
);
};
export default List;
