// frontend-react/pages/module/admin/view/referetiel/acess-share-admin/view-admin/acess-share-view-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";
import  {AcessShareDto}  from '/pages/controller/model/AcessShare.model';

const View = ({visible,onClose,selectedItem}) => {

    const emptyItem = new AcessShareDto();
    const [item, setItem] = useState<AcessShareDto>(emptyItem);
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);

    useEffect(() => {
        setItem(selectedItem ? { ...selectedItem } : { ...emptyItem });
    }, [selectedItem]);

    const onTabChange = (e: { index: number }) => {
        setActiveIndex(e.index);
    };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} /> < />
    );

return(
<Dialog visible={visible} style={{width: '70vw'}} header="AcessShare Details" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header="AcessShare">
    <div className="formgrid grid">

            <div className="field col-6">
                <label htmlFor="code">Code</label>
                <InputText id="code" value={selectedItem?.code} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="libelle">Libelle</label>
                <InputText id="libelle" value={selectedItem?.libelle} disabled   />
            </div>

        </div>
</TabPanel>
</TabView>
</Dialog>
);
};
export default View;

// frontend-ang/src/app/module/admin/view/referetiel/acess-share-admin/view-admin/acess-share-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {AcessShareService} from 'src/app/controller/service/AcessShare.service';
import {AcessShareDto} from 'src/app/controller/model/AcessShare.model';
import {AcessShareCriteria} from 'src/app/controller/criteria/AcessShareCriteria.model';

@Component({
  selector: 'app-acess-share-view-admin',
  templateUrl: './acess-share-view-admin.component.html'
})
export class AcessShareViewAdminComponent extends AbstractViewController<AcessShareDto, AcessShareCriteria, AcessShareService> implements OnInit {


    constructor(private acessShareService: AcessShareService){
        super(acessShareService);
    }

    ngOnInit(): void {
    }




}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'acessShareTabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'acessShareTabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'Code' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Code' | translate}}" autofocus  id="1" [(ngModel)]="item.code">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'Libelle' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Libelle' | translate}}" autofocus  id="2" [(ngModel)]="item.libelle">
                    </div>
                </div>
            </p-tabPanel>

        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>
