// frontend-ang/src/app/module/admin/view/user/groupe-admin/create-admin/groupe-create-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';

import { AbstractCreateController } from 'src/app/zynerator/controller/AbstractCreateController';

import {GroupeService} from 'src/app/controller/service/Groupe.service';
import {GroupeDto} from 'src/app/controller/model/Groupe.model';
import {GroupeCriteria} from 'src/app/controller/criteria/GroupeCriteria.model';
import {UtilisateurDto} from 'src/app/controller/model/Utilisateur.model';
import {UtilisateurService} from 'src/app/controller/service/Utilisateur.service';
import {GroupeUtilisateurDto} from 'src/app/controller/model/GroupeUtilisateur.model';
import {GroupeUtilisateurService} from 'src/app/controller/service/GroupeUtilisateur.service';
@Component({
  selector: 'app-groupe-create-admin',
  templateUrl: './groupe-create-admin.component.html'
})
export class GroupeCreateAdminComponent extends AbstractCreateController<GroupeDto, GroupeCriteria, GroupeService>  implements OnInit {

    private _groupeUtilisateursElement = new GroupeUtilisateurDto();


   private _validGroupeCode = true;
   private _validGroupeLibelle = true;
    private _validUtilisateurEmail = true;
    private _validUtilisateurName = true;
    private _groupeUtilisateurs: Array<GroupeUtilisateurDto> = [];

    constructor( private groupeService: GroupeService , private utilisateurService: UtilisateurService, private groupeUtilisateurService: GroupeUtilisateurService) {
        super(groupeService);
    }

    ngOnInit(): void {
        this.utilisateurService.findAll().subscribe(data => this.prepareGroupeUtilisateurs(data));
        this.groupeUtilisateursElement.utilisateur = new UtilisateurDto();
        this.utilisateurService.findAll().subscribe((data) => this.utilisateurs = data);
    this.utilisateur = new UtilisateurDto();
    this.utilisateurService.findAll().subscribe((data) => this.utilisateurs = data);
}


     prepareGroupeUtilisateurs(utilisateurs: Array<UtilisateurDto>): void{
        if( utilisateurs != null){
                utilisateurs.forEach(e => {
                const groupeUtilisateur = new GroupeUtilisateurDto();
                groupeUtilisateur.utilisateur = e;
                this.groupeUtilisateurs.push(groupeUtilisateur);
            });
        }
    }



    public setValidation(value: boolean){
        this.validGroupeCode = value;
        this.validGroupeLibelle = value;
    }



    public validateForm(): void{
        this.errorMessages = new Array<string>();
        this.validateGroupeCode();
        this.validateGroupeLibelle();
    }

    public validateGroupeCode(){
        if (this.stringUtilService.isEmpty(this.item.code)) {
        this.errorMessages.push('Code non valide');
        this.validGroupeCode = false;
        } else {
            this.validGroupeCode = true;
        }
    }
    public validateGroupeLibelle(){
        if (this.stringUtilService.isEmpty(this.item.libelle)) {
        this.errorMessages.push('Libelle non valide');
        this.validGroupeLibelle = false;
        } else {
            this.validGroupeLibelle = true;
        }
    }


    public async openCreateUtilisateur(utilisateur: string) {
    const isPermistted = await this.roleService.isPermitted('Utilisateur', 'add');
    if(isPermistted) {
         this.utilisateur = new UtilisateurDto();
         this.createUtilisateurDialog = true;
    }else{
        this.messageService.add({
        severity: 'error', summary: 'erreur', detail: 'problème de permission'
        });
     }
    }

    get utilisateur(): UtilisateurDto {
        return this.utilisateurService.item;
    }
    set utilisateur(value: UtilisateurDto) {
        this.utilisateurService.item = value;
    }
    get utilisateurs(): Array<UtilisateurDto> {
        return this.utilisateurService.items;
    }
    set utilisateurs(value: Array<UtilisateurDto>) {
        this.utilisateurService.items = value;
    }
    get createUtilisateurDialog(): boolean {
       return this.utilisateurService.createDialog;
    }
    set createUtilisateurDialog(value: boolean) {
        this.utilisateurService.createDialog= value;
    }

    get groupeUtilisateurs(): Array<GroupeUtilisateurDto> {
        if( this._groupeUtilisateurs == null )
            this._groupeUtilisateurs = new Array();
        return this._groupeUtilisateurs;
    }

    set groupeUtilisateurs(value: Array<GroupeUtilisateurDto>) {
        this._groupeUtilisateurs = value;
    }


    get validGroupeCode(): boolean {
        return this._validGroupeCode;
    }

    set validGroupeCode(value: boolean) {
         this._validGroupeCode = value;
    }
    get validGroupeLibelle(): boolean {
        return this._validGroupeLibelle;
    }

    set validGroupeLibelle(value: boolean) {
         this._validGroupeLibelle = value;
    }

    get validUtilisateurEmail(): boolean {
        return this._validUtilisateurEmail;
    }
    set validUtilisateurEmail(value: boolean) {
        this._validUtilisateurEmail = value;
    }
    get validUtilisateurName(): boolean {
        return this._validUtilisateurName;
    }
    set validUtilisateurName(value: boolean) {
        this._validUtilisateurName = value;
    }

    get groupeUtilisateursElement(): GroupeUtilisateurDto {
        if( this._groupeUtilisateursElement == null )
            this._groupeUtilisateursElement = new GroupeUtilisateurDto();
        return this._groupeUtilisateursElement;
    }

    set groupeUtilisateursElement(value: GroupeUtilisateurDto) {
        this._groupeUtilisateursElement = value;
    }

}

        <p-dialog [(visible)]="createDialog" [style]="{width: '70vw'}" header="{{'groupeTabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                        <p-tabView>
                            <p-tabPanel header="{{'groupeTabPan' | translate}}">
                                <div class="grid">

                                                <div class="field col-12 md:col-6">
                                                    <label for="1">{{'groupeCode' | translate}}<span style="color: red;">*</span></label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'groupeCode' | translate}}" id="1" [(ngModel)]="item.code"
                                                            [ngClass]="{'ng-invalid ng-dirty' : !validGroupeCode}"  />
                                                    <small class='p-error' *ngIf='!validGroupeCode'>Code est obligatoire.</small>
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="2">{{'groupeLibelle' | translate}}<span style="color: red;">*</span></label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'groupeLibelle' | translate}}" id="2" [(ngModel)]="item.libelle"
                                                            [ngClass]="{'ng-invalid ng-dirty' : !validGroupeLibelle}"  />
                                                    <small class='p-error' *ngIf='!validGroupeLibelle'>Libelle est obligatoire.</small>
                                                </div>



                                            <div class="field col-11 md:col-5">
                                                <label for="3">{{'groupeUtilisateur' | translate}}</label>
                                                <p-dropdown  appendTo="body"  [options]="utilisateurs" [(ngModel)]="item.utilisateur" id="3" [filter]="true" filterMatchMode="contains"
                                                        [showClear]="true" optionLabel="name" placeholder="{{'groupeUtilisateur' | translate}}"  >
                                                </p-dropdown>
                                                
                                            </div>
                                                <div class="col-1">
                                                    <label></label>
                                                    <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateUtilisateur('Utilisateur')" class="p-button-success one-colonne-btn-success-align"></button>
                                                </div>
                                            <div class="field col-12  md:col-6">
                                                <label>Utilisateur</label>
                                                <p-multiSelect [options]="groupeUtilisateurs" [(ngModel)]="item.groupeUtilisateurs" itemSize="30" [virtualScroll]="true"
                                                                                                                          defaultLabel="Select un utilisateur" optionLabel="utilisateur.name"  display="chip"></p-multiSelect>
                                            </div>
                                </div>
                            </p-tabPanel>

                        </p-tabView>

            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-step">
                        <div style="margin-left: auto;">
                            <button pButton pRipple  label="{{'validate' | translate}}"  icon="pi pi-check" style="margin:10px" (click)="save()"></button>
                        </div>
                        <div>
                            <button pButton pRipple  label="{{'cancel' | translate}}" icon="pi pi-times" class="p-button-outlined" (click)="hideCreateDialog()"></button>
                        </div>

                </div>
            </ng-template>

            <app-utilisateur-create-admin></app-utilisateur-create-admin>

            <app-utilisateur-create-admin></app-utilisateur-create-admin>

    </p-dialog>

// frontend/pages/module/admin/view/user/groupe-admin/create-admin/groupe-create-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import {InputNumberChangeEvent} from 'primereact/inputnumber';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";
import {MessageService} from "/pages/controller/service/MessageService";
import {GroupeService} from '/pages/controller/service/Groupe.service';
import  {GroupeDto}  from '/pages/controller/model/Groupe.model';
import {GroupeUtilisateurDto} from '/pages/controller/model/GroupeUtilisateur.model';
import {GroupeUtilisateurService} from '/pages/controller/service/GroupeUtilisateur.service';
import {UtilisateurDto} from '/pages/controller/model/Utilisateur.model';
import {UtilisateurService} from '/pages/controller/service/Utilisateur.service';
const Create = ({visible, onClose, add, showToast, list}) => {

    const emptyItem = new GroupeDto();
    const [items, setItems] = useState<GroupeDto[]>([list]);
    const [item, setItem] = useState<GroupeDto>(emptyItem);
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);
    const [activeTab, setActiveTab] = useState(0);

    const [utilisateurs, setUtilisateurs] = useState<UtilisateurDto[]>([]);

    type GroupeUtilisateurResponse = AxiosResponse<GroupeUtilisateurDto[]>;
    type UtilisateurResponse = AxiosResponse<UtilisateurDto[]>;

    const [groupeUtilisateurs, setGroupeUtilisateurs] = useState<GroupeUtilisateurDto>(new GroupeUtilisateurDto());

    useEffect(() => {
        const fetchData = async () => {
            try {
                const [utilisateursResponse ] = await Promise.all<UtilisateurResponse>([
                    UtilisateurService.getList(),
                ]);
                setUtilisateurs(utilisateursResponse.data);
            } catch (error) {
                console.error(error);
            }
        };
        fetchData();
    }, []);

    const onDropdownChange = (e, field) => {
        setItem((prevState) => ({ ...prevState, [field]: e.value}));
    };


    const onTabChange = (e: { index: number }) => { setActiveIndex(e.index); };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const saveItem = async () => {
        setSubmitted(true);
        let _items = [...items];
        let _item = {...item};
        if (!_item.id) {
            const response = await GroupeService.save(_item);
			_item.id = response.data.id;
            _items.push(_item);
            add(_item);
            MessageService.showToast(showToast, { severity: 'success', summary: 'Successful', detail: 'Groupe Created', life: 3000 });
        }
        setItems(_items);
        onClose();
        setItem(emptyItem);
        setItem({...item, GroupeUtilisateurs: null, });
        setGroupeUtilisateurs(new GroupeUtilisateurDto());
    };

    const onInputTextChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>, name: string) => {
        const val = (e.target && e.target.value) || '';
        let _item = {...item};
        _item[`${name}`] = val;
        setItem(_item);
    };

    const onInputDateChange = (e: CalendarChangeEvent, name: string) => {
        const val = e.value || '';
        let _item = { ...item};
        _item[`${name}`] = val;
        setItem(_item);
    };

    const onInputNumerChange = (e: InputNumberChangeEvent, name: string) => {
        const val = e.value === null ? null : +e.value;
        setItem((prevItem) => ({ ...prevItem, [name]: val, }));
    };

    const onMultiSelectChange = (e, field) => {
      if (e && e.value && Array.isArray(e.value)) {
         const selectedValues = e.value.map(option => option && option.value);
         setItem(prevState => ({ ...prevState, [field]: selectedValues, }));
      }
    };

    const onBooleanInputChange = (e: any, name: string) => {
       const val = e.value;
       setItem((prevItem) => ({ ...prevItem, [name]: val, }));
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} />
        <Button label="Save" icon="pi pi-check" text onClick={saveItem} /> < />
    );

return(
    <Dialog visible={visible} style={{width: '70vw'}} header="Groupe" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header="Groupe">
                <div className="formgrid grid">
                    <div className="field col-6">
                    <label htmlFor="code">Code</label>
                    <InputText id="code" value={item.code} onChange={(e) => onInputTextChange(e, 'code')} required autoFocus className={classNames({'p-invalid': submitted && !item.code})} />
                    {submitted && !item.code && <small className="p-invalid">Code is required.</small>}
                    </div>
                    <div className="field col-6">
                    <label htmlFor="libelle">Libelle</label>
                    <InputText id="libelle" value={item.libelle} onChange={(e) => onInputTextChange(e, 'libelle')} required autoFocus className={classNames({'p-invalid': submitted && !item.libelle})} />
                    {submitted && !item.libelle && <small className="p-invalid">Libelle is required.</small>}
                    </div>
                    <div className="field col-6">
                    <label htmlFor="utilisateur">Utilisateur</label>
                    <Dropdown  id="utilisateurDropdown"  value={item.utilisateur} options={utilisateurs} onChange={(e) => onDropdownChange(e, 'utilisateur')}   placeholder="Sélectionnez un utilisateur" filter filterPlaceholder="Rechercher un utilisateur" optionLabel="name" />
                    </div>
                    <div className="field col-6">
                    <label htmlFor="groupeUtilisateurs">Utilisateur</label>
                    <MultiSelect value={item.groupeUtilisateurs} options={groupeUtilisateurs}  optionLabel="utilisateur.name" display="chip" placeholder="Select utilisateur"  maxSelectedLabels={3}  onChange={(e) => onMultiSelectChange(e, 'groupeUtilisateurs')} />
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Create;
